services:
    sonata.admin.users:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "blog", label: "Users" }

    sonata.admin.articles:
        class: AppBundle\Admin\ArticleAdmin
        arguments: [ ~, AppBundle\Entity\Article, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "blog", label: "Articles" }

    sonata.admin.categories:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [ ~, AppBundle\Entity\Category, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "blog", label: "Category" }

    sonata.admin.tags:
        class: AppBundle\Admin\TagAdmin
        arguments: [ ~, AppBundle\Entity\Tag, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "blog", label: "Tag" }


