services:
    sonata.admin.users:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "blog", label: "Users" }